name: Check Rate Limit

on:
  workflow_dispatch:

jobs:
  check-rate-limit:
    runs-on: ubuntu-latest

    steps:
      - name: Check Rate Limit
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }} # Ensure this is set correctly
        run: |
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/rate_limit)
          
          echo "Rate limit response: $response"
