name: Move Files in Specific Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'feat:clear-clutter'
        required: true
        default: 'main'

jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Specific Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyGithub

    - name: Run Python Script
      env:
        MY_PAT: ${{ secrets.MY_PAT }}  # Replace this with your actual PAT or store it in GitHub Secrets
      run: python move_files.py
