name: Auto Label and Comment on PR

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  label-and-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add hacktoberfest-accepted label
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          -d '{"labels":["hacktoberfest-accepted"]}'

      - name: Post comment
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d '{"body": "This PR is under review"}'
