name: Merge and Greet All Open PRs

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  merge_and_greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: List, merge, and thank
        run: |
          # List all open pull requests and get their numbers
          prs=$(gh pr list --state open --json number --jq '.[].number')

          # Loop through each open PR and merge using admin privileges
          for pr in $prs; do
            echo "Merging PR #$pr"
            gh pr merge $pr --admin --squash  # Force merge with admin privileges

            # Add a thank you comment
            echo "Thanking contributor for PR #$pr"
            gh pr comment $pr --body "Thank you for contributing! 🎉 Your PR has been merged."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
