name: Merge and Greet Specific Pull Requests

on:
  workflow_dispatch:

jobs:
  merge_and_greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Merge and thank contributors for specific PRs
        run: |
          # Specify the PR numbers to merge
          prs=(575 576)

          # Loop through each specified PR and merge using admin privileges
          for pr in "${prs[@]}"; do
            echo "Merging PR #$pr"
            
            # Force merge with admin privileges for both PRs
            gh pr merge $pr --admin --squash

            # Add a thank you comment
            echo "Thanking contributor for PR #$pr"
            gh pr comment $pr --body "Thank you for contributing! 🎉 Your PR has been merged."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
