name: Merge and Greet All Open Pull Requests

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  merge_and_greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: List, merge, and thank contributors for all open pull requests
        run: |
          # Fetch all open PRs, with a limit of 100
          prs=$(gh pr list --state open --json number --jq '.[].number' --limit 100)
          
          # Check if no PRs are found
          if [ -z "$prs" ]; then
            echo "No more PRs to merge."
            exit 0
          fi

          # Loop through each PR and merge
          for pr in $prs; do
            echo "Merging PR #$pr"
            gh pr merge $pr --admin --squash  # Force merge with admin privileges

            # Add a thank you comment
            echo "Thanking contributor for PR #$pr"
            gh pr comment $pr --body "Thank you for contributing! 🎉 Your PR has been merged."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
